config/routes.rb
Rails.application.routes.draw do
  resources :databases

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :forms do
    get :autocomplete_examination_doctor, :on => :collection
    get :autocomplete_examination_program, :on => :collection
    get :autocomplete_filling_area, :on => :collection
  end
  resources :fillings
  resources :databases

  get '/inactive', to: 'users#index_inactive', as: :inactive
  get '/manage', to: 'users#index', as: :manage
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  post '/enable/:id',  to: 'users#enable'    , as: :enable
  match '/forms/:id/fill', to: 'forms#fill'  , as: :fill      , via: [:post, :patch]
  match '/fillings/:id/edit', to: 'forms#edit_fill'  , as: :edit_fill      , via: [:post, :patch]
  get '/forms/:id/stats', to: 'forms#stats', as: :stats
  get '/forms/:id/fillings', to: 'fillings#form_index', as: :fillings_index

  root to: 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  

end

app/models/filling.rb
require 'csv'

class Filling < ActiveRecord::Base
  belongs_to :form
  has_many :answers, dependent: :destroy
  has_many :examinations, dependent: :destroy
  accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :examinations, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :form_id
  validates :serial, :numericality => { :greater_than_or_equal_to => 0 }
  validates :serial, uniqueness: { scope: :form_id,
                                 message: 'serial should be unique in the scope of every form' }


  def self.to_csv
    CSV.generate do |csv|
      @questions = ['Αύξων Αριθμός', 'Περιοχή', 'Ημερομηνία', 'Εξέταση', 'Ιατρός', 'Πρόγραμμα']
      unless all.first.nil?
        all.first.form.questions.reverse.each do |question|
          @questions << question.description
        end
        csv << @questions
        all.each do |filling|
          filling.examinations.each do |examination|
            @filling = []
            @filling << filling.serial
            @filling << filling.area
            @filling << examination.date
            @filling << examination.content
            @filling << examination.doctor
            @filling << examination.program
            filling.answers.order(question_id: :asc).each do |answer|
              @content = answer.content
              if @content.nil? or @content.empty?
                @choices = []
                answer.picks.each do |pick|
                  @choices << pick.choice.content.to_s.strip
                end
                @filling << @choices.join(', ')
              else
                @filling << answer.content.to_s.strip
              end
            end
            csv << @filling
          end
        end
      end
    end
  end


end

app/controllers/fillings_controller.rb
class FillingsController < ApplicationController

  before_action :authenticate_user!, only: [:form_index, :index, :show, :new, :create, :edit, :update, :destroy]
  before_action :authenticate_destroy!, only: [:edit, :update, :destroy]

  def index
    @fillings = Filling.all
  end

  def form_index
    @form = Form.find(params[:id])
    @fillings = @form.fillings.order(:serial)
    respond_to do |format|
      format.html
      format.csv { send_data @fillings.to_csv }
      format.xls
    end
  end

  def show
    @filling = Filling.find(params[:id])
    @show = TRUE
  end

  def edit
    @filling = Filling.find(params[:id])
    @examination = @filling.examinations.build
    @show = FALSE
  end

  def destroy
    @filling = Filling.find(params[:id])
    @form = @filling.form
    @filling.destroy
    redirect_to fillings_index_path(:id => @form.id), :flash => {:success => "Filling removed."}
  end


end

app/helpers/fillings_helper.rb
module FillingsHelper
end

app/views/fillings/_checkbox_answer_fields.html.erb
<tr>
    <td>
        <div class="checkbox">
            <label>
                <input type="checkbox" name="<%= question_id %>[]" value="<%= choice_id %>" <%= params[question_id.to_s] && params[question_id.to_s].include?(choice_id.to_s) ? "checked" : "" %>> <%= content %>
            </label>
        </div>
    </td>
</tr>

app/views/fillings/_date_answer_fields.html.erb
<input class="big datepicker" type="text" name="<%= question_id %>" value="<%= params[question_id.to_s] %>" data-provider='datepicker' autoclose="true">
<span class="glyphicon glyphicon-calendar"></span>

<script type="text/javascript">
    $('.datepicker').datepicker({
        autoclose: true,
        format: 'dd/mm/yyyy',
        todayHighlight: true
    });
</script>

app/views/fillings/_denture_answers_fields.html.erb
<input class="big" type="text" name="<%= question.id %>" value="<%= params[question.id.to_s] %>">

<% if false %>

<table class="table" style="empty-cells: hide">
  <tr>
    <% question.choices[0..7].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[8] %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
    </td>
    <% question.choices[9..15].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
  <tr>
    <% question.choices[16..23].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[24] %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
    </td>
    <% question.choices[25..31].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
  <tr>
    <% 16.times do %>
    <td>&nbsp;</td>
    <% end %>
    <% question.choices[32..36].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[37] %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
    </td>
    <% question.choices[38..41].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
  <tr>
    <% 16.times do %>
        <td>&nbsp;</td>
    <% end %>
    <% question.choices[42..46].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[47] %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
    </td>
    <% question.choices[48..51].each do |choice| %>
        <td>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" value="<%= choice.id %>" <%= params[question.id.to_s] && params[question.id.to_s].include?(choice.id.to_s) ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
</table>

<% end %>

app/views/fillings/_dropdown_answer_fields.html.erb
<option name="<%= question_id %>" value="<%= choice_id %>" <%= choice_id.to_s == params[question_id.to_s] ? "checked" : "" %>><%= content %></option>

app/views/fillings/_examination.html.erb
<div class="nested-fields transparent-box">

  <% if @filling.form.date_enabled or @filling.form.content_enabled or @filling.form.doctor_enabled or @filling.form.program_enabled %>
<h3>Εξέταση <%= count %></h3>
      <% if count == 1 %>
          <h6>(Η πρώτη εξέταση για τον συγκεκριμένο ασθενή, όταν υποβληθεί η φόρμα θα είναι διαθέσιμη και η
            δεύτερη)</h6>
      <% end %>
      <% if @filling.form.date_enabled %>
          <h4>Ημερομηνία</h4><h6>(ΗΗ/ΜΜ/ΕΕΕΕ)</h6>
<% if disabled %>
      <%= e.text_field :date, :value => date, :class => 'big datepicker', 'data-provider' => 'datepicker', 'autoclose' => 'true', 'disabled' => 'true' %>
  <% else %>
      <%= e.text_field :date, :value => date, :class => 'big datepicker', 'data-provider' => 'datepicker', 'autoclose' => 'true' %>
  <% end %>
  <span class="glyphicon glyphicon-calendar"></span>
      <% end %>

      <% if @filling.form.content_enabled %>
<h4>Παρατηρήσεις</h4>
<% if disabled %>
    <%= e.text_area :content, :class => 'form-control', :rows => '3', 'disabled' => 'true' %>
<% else %>
      <%= e.text_area :content, :class => 'form-control', :rows => '3' %>
<% end %>
      <% end %>

      <% if @filling.form.doctor_enabled %>
          <h4>Γιατρός</h4>
          <% if disabled %>
              <%= e.autocomplete_field :doctor, autocomplete_examination_doctor_forms_path, :class => 'form-control', 'disabled' => 'true' %>
          <% else %>
              <%= e.autocomplete_field :doctor, autocomplete_examination_doctor_forms_path, :class => 'form-control' %>
          <% end %>
      <% end %>

      <% if @filling.form.doctor_enabled %>
          <h4>Πρόγραμμα</h4>
          <% if disabled %>
              <%= e.autocomplete_field :program, autocomplete_examination_program_forms_path, :class => 'form-control', 'disabled' => 'true' %>
          <% else %>
              <%= e.autocomplete_field :program, autocomplete_examination_program_forms_path, :class => 'form-control' %>
          <% end %>
      <% end %>


      </div>
  <% end %>
<script type="text/javascript">
    $('.datepicker').datepicker({
        autoclose: true,
        format: 'dd/mm/yyyy',
        todayHighlight: true
    });
</script>

app/views/fillings/_filled_checkbox_answer_fields.html.erb
<tr>
  <td>
    <div class="checkbox">
      <label>
        <input type="checkbox" name="<%= question_id %>[]" value="<%= choice_id %>" <%= @show ? 'disabled="true"' : '' %> <%= !checked ? "checked" : "" %> > <%= content %>
      </label>
    </div>
  </td>
</tr>

app/views/fillings/_filled_denture_answers_fields.html.erb
<table class="table" style="empty-cells: hide">
  <tr>
    <% question.choices[0..7].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[8] %>
      <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
    </td>
    <% question.choices[9..15].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
  <tr>
    <% question.choices[16..23].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[24] %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
    </td>
    <% question.choices[25..31].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw(raw('disabled="true"')) : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
  <tr><td></td></tr>
  <tr>
      <% question.choices[32..36].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[37] %>
      <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
    </td>
    <% question.choices[38..41].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
  <tr>
    <% question.choices[42..46].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
    <td style="border-left: 1px solid">
      <% choice = question.choices[47] %>
      <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
      <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
    </td>
    <% question.choices[48..51].each do |choice| %>
        <td>
          <% checked = @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
          <%= choice.content %><br /><input type="checkbox" name="<%= question.id %>[]" <%= @show ? raw('disabled="true"') : '' %> value="<%= choice.id %>" <%= !checked ? "checked" : "" %>>
        </td>
    <% end %>
  </tr>
</table>

app/views/fillings/_filled_multiple_answer_fields.html.erb
<tr>
    <td>
      <div class="radio">
        <label>
          <input type="radio" name="<%= question_id %>" value="<%= choice_id %>" <%= @show ? 'disabled="true"' : '' %> <%= !checked ? "checked" : "" %> > <%= content %>
        </label>
      </div>
    </td>
</tr>

app/views/fillings/_filled_number_answer_fields.html.erb
<input class="big" type="number" name="<%= question_id %>" <%= @show ? 'disabled="true"' : '' %> value="<%= content %>">

app/views/fillings/_filled_text_answer_fields.html.erb
<input class="big" type="text" name="<%= question_id %>" <%= @show ? 'disabled="true"' : '' %> value="<%= content %>">

app/views/fillings/_number_answer_fields.html.erb
<input class="big" type="number" name="<%= question_id %>" value="<%= params[question_id.to_s] %>">

app/views/fillings/_text_answer_fields.html.erb
<input class="big" type="text" name="<%= question_id %>" value="<%= params[question_id.to_s] %>">

app/views/fillings/form_index.html.erb
<div class="container col-xs-7 center text-center">


  <h2>Fillings of <%= @form.title %></h2>

  <%= link_to raw('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Fill'),
              form_path(@form),
              class: 'btn btn-default btn-lg',
              method: :get %>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#statsModal">
    <span class="glyphicon glyphicon-stats" aria-hidden="true"></span> Stats
  </button>

  <table id="fillings" class="table-bordered display">
  <thead>
  <tr>
    <th>Αύξων Αριθμός</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @fillings.each do |filling| %>
      <tr>
        <td><%= filling.serial %></td>
        <td><%= link_to 'Show', filling %></td>
        <td><%= link_to 'Edit', edit_filling_path(filling) %></td>
        <td><%= link_to 'Destroy', filling, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

</div>

<!-- Modal -->
<div class="modal fade" id="statsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form action="<%= stats_path %>">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Stats Selection</h4>
        </div>
        <div class="modal-body">


          <div id="examination">
            <h3>Ενεργά Πεδία Αναζήτησης</h3>
            <% if @form.date_enabled %>
                <div class="form-group form-inline">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="date"> Ημερομηνία
                    </label>&nbsp;&nbsp;&nbsp;
                    Από: <input class="datepicker" type="text" name="from" data-provider='datepicker' autoclose="true">
                    <span class="glyphicon glyphicon-calendar"></span>
                    Έως: <input class="datepicker" type="text" name="to" data-provider='datepicker' autoclose="true">
                    <span class="glyphicon glyphicon-calendar"></span>
                  </div>
                </div>
            <% end %>
            <% if @form.area_enabled %>
                <div class="form-group form-inline">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="area"> Περιοχή
                    </label>
                  </div>
                </div>
            <% end %>
            <% if false and @form.content_enabled %>
                <div class="form-group form-inline">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="content"> Παρατηρήσεις
                    </label>&nbsp;&nbsp;&nbsp;
                    Χαρακτήρας: <input type="text" name="delimiter" value="#">
                  </div>
                </div>
            <% end %>
            <% if @form.doctor_enabled %>
                <div class="form-group form-inline">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="doctor"> Ιατρός
                    </label>
                  </div>
                </div>
            <% end %>
            <% if @form.program_enabled %>
                <div class="form-group form-inline">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="program"> Πρόγραμμα
                    </label>
                  </div>
                </div>
            <% end %>
          </div>
          <h3>Επιλογή Από Συμπληρωματικές Ερωτήσεις</h3>

          <div class="form-group form-inline">
            <div class="checkbox">
              <label>
                <input type="radio" name="question" value=""> Καμία
              </label>
            </div>
          </div>

          <% @form.questions.each do |q| %>
              <% if q.category == 'text' or q.category == 'number' %>
                  <div class="form-group form-inline">
                    <div class="checkbox">
                      <label>
                        <input type="radio" name="question" value=<%= q.id %>> <%= q.description %>
                      </label>
                    </div>
                  </div>
              <% end %>
          <% end %>


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-stats"></span> Search
          </button>
        </div>
      </form>
    </div>
  </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#fillings').dataTable();
    });
</script>

<script type="text/javascript">
    $('.datepicker').datepicker({
        autoclose: true,
        format: 'dd/mm/yyyy',
        todayHighlight: true
    });
</script>

app/views/fillings/show.html.erb
<div class="container col-xs-7 center text-center">
  <h2><%= link_to @filling.form.title, fillings_index_path(@filling.form) %></h2>

  <%= link_to raw('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit'),
              edit_filling_path(@filling),
              class: 'btn btn-default btn-lg',
              method: :get %>

  <%= link_to raw('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Refill'),
              form_path(@filling.form),
              class: 'btn btn-default btn-lg',
              method: :get %>

  <%= form_for @filling do |f| %>
      <%= f.hidden_field :form_id, :value => params[:id] %>
      <div class="transparent-box">
        <h4>Αύξων Αριθμός Ασθενούς</h4>
        <%= f.number_field :serial, :disabled => true, :class => 'big' %>
      </div>
      <% if @filling.form.area_enabled %>
          <div class="transparent-box">
            <h4>Περιοχή</h4>
            <%= f.text_field :area, :disabled => true, :class => 'big' %>
          </div>
      <% end %>
      <% @filling.form.questions.reverse.each do |question| %>
          <div class="nested-fields transparent-box">
            <h4><%= question.description %></h4>
            <% if question.category == "text" %>
                <%= render :partial => "/fillings/filled_text_answer_fields", :locals => {:question_id => question.id, :content => @filling.answers.where(:question_id => question.id.to_s).first.content} %>
            <% elsif question.category == "number" %>
                <%= render :partial => "/fillings/filled_number_answer_fields", :locals => {:question_id => question.id, :content => @filling.answers.where(:question_id => question.id.to_s).first.content} %>
            <% elsif question.category == "date" %>
                <h6>(ΗΗ/ΜΜ/ΕΕΕΕ)</h6>
                <%= render :partial => "/fillings/filled_date_answer_fields", :locals => {:question_id => question.id, :date => @filling.answers.where(:question_id => question.id.to_s).first.date} %>
            <% elsif question.category == "multiple" %>
                <table class="table table-nonfluid text-left">
                  <% question.choices.each do |choice| %>
                      <%= render :partial => "/fillings/filled_multiple_answer_fields", :locals => {:question_id => question.id, :content => choice.content, :choice_id => choice.id, :checked => @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty?} %>
                  <% end %>
                </table>
            <% elsif question.category == "checkbox" %>
                <table class="table table-nonfluid text-left">
                  <% question.choices.each do |choice| %>
                      <%= render :partial => "/fillings/filled_checkbox_answer_fields", :locals => {:question_id => question.id, :content => choice.content, :choice_id => choice.id, :checked => @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty?} %>
                  <% end %>
                </table>
            <% elsif question.category == "denture" %>
                <%= render :partial => "/fillings/filled_denture_answers_fields", :locals => {:question => question} %>
            <% elsif question.category == "dropdown" %>
                <select disabled class="form-control" name="<%= question.id %>">
                  <% question.choices.each do |choice| %>
                      <% unless @filling.answers.where(:question_id => question.id.to_s).first.picks.where(:choice_id => choice.id).empty? %>
                          <%= render :partial => "/fillings/filled_dropdown_answer_fields", :locals => {:question_id => question.id, :content => choice.content, :choice_id => choice.id} %>
                      <% end %>
                  <% end %>
                </select>
            <% end %>

          </div>
      <% end %>
      <% @count = 1 %>
      <%= f.fields_for :examinations, f.object.examinations do |e| %>
          <%= render :partial => '/fillings/examination', :locals => {:e => e, :disabled => TRUE, :count => @count, :date => e.object.date.blank? ? '' : e.object.date.strftime('%d/%m/%Y')} %>
          <% @count += 1 %>
      <% end %>

  <% end %>
</div>
<!-- /container -->