config/routes.rb
Rails.application.routes.draw do
  resources :databases

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :forms do
    get :autocomplete_examination_doctor, :on => :collection
    get :autocomplete_examination_program, :on => :collection
    get :autocomplete_filling_area, :on => :collection
  end
  resources :fillings
  resources :databases

  get '/inactive', to: 'users#index_inactive', as: :inactive
  get '/manage', to: 'users#index', as: :manage
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  post '/enable/:id',  to: 'users#enable'    , as: :enable
  match '/forms/:id/fill', to: 'forms#fill'  , as: :fill      , via: [:post, :patch]
  match '/fillings/:id/edit', to: 'forms#edit_fill'  , as: :edit_fill      , via: [:post, :patch]
  get '/forms/:id/stats', to: 'forms#stats', as: :stats
  get '/forms/:id/fillings', to: 'fillings#form_index', as: :fillings_index

  root to: 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :forms, dependent: :destroy

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @users = User.where(admin: false).reorder("email ASC").paginate(page: params[:page], :per_page => 10)
  end
  
  def index_inactive
    @users = User.where(approved: false).reorder("email ASC").paginate(page: params[:page], :per_page => 10)
  end
  
  def enable
    @user = User.find(params[:id])
    @user.toggle!(:approved)
    respond_to do |format|
      flash[:success] = "User with #{@user.email} has been approved"
      format.html { redirect_to inactive_path }
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to :back, notice: "User deleted"
    end
    rescue ActionController::RedirectBackError
      redirect_to root_path
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container col-xs-6 center">

<% unless @users.empty? %>
  <div class="margin-top text-center">
  <h2>Users</h2>
  </div>
<% else %>
  <div class="margin-top text-center">
  <h2>There are no registrations pending approval</h2>
  </div>
<% end %>

<%= will_paginate @users %>

<table class="table table-striped">
<% @users.each do |user| %>
<tr>
  <td><%= user.email %></td>
  <td><%= form_tag admin_destroy_user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "form-inline" do %>
    <%= submit_tag "Delete", name: nil, class: "btn btn-default btn-danger" %>
<% end %></td>
</tr>
<% end %>
</table>
<%= will_paginate @users %>
</div>

app/views/users/index_inactive.html.erb
<div class="container col-xs-6 center">

<% unless @users.empty? %>
  <div class="margin-top text-center">
  <h2>Inactive Users</h2>
  </div>
<% else %>
  <div class="margin-top ">
  <h2>There are no registrations pending approval</h2>
  </div>
<% end %>

<%= will_paginate @users %>

<table class="table table-striped">
<% @users.each do |user| %>
<tr>
  <td><%= user.email %></td>
  <td><%= form_tag enable_path(user.id), method: :post, :class => "form-inline" do %>
    <%= submit_tag "Enable", name: nil, class: "btn btn-default btn-success" %>
<% end %></td>
  <td><%= form_tag admin_destroy_user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "form-inline" do %>
    <%= submit_tag "Delete", name: nil, class: "btn btn-default btn-danger" %>
<% end %></td>
</tr>
<% end %>
</table>
<%= will_paginate @users %>
</div>