config/routes.rb
Rails.application.routes.draw do
  resources :databases

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :forms do
    get :autocomplete_examination_doctor, :on => :collection
    get :autocomplete_examination_program, :on => :collection
    get :autocomplete_filling_area, :on => :collection
  end
  resources :fillings
  resources :databases

  get '/inactive', to: 'users#index_inactive', as: :inactive
  get '/manage', to: 'users#index', as: :manage
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  post '/enable/:id',  to: 'users#enable'    , as: :enable
  match '/forms/:id/fill', to: 'forms#fill'  , as: :fill      , via: [:post, :patch]
  match '/fillings/:id/edit', to: 'forms#edit_fill'  , as: :edit_fill      , via: [:post, :patch]
  get '/forms/:id/stats', to: 'forms#stats', as: :stats
  get '/forms/:id/fillings', to: 'fillings#form_index', as: :fillings_index

  root to: 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  before_action :authenticate_user!, only: [:fill, :edit_fill, :stats, :index, :show, :new, :create, :edit, :update, :destroy]
  before_action :authenticate_destroy!, only: [:edit, :update, :destroy]

  def new
    @form = Form.new
  end
  
  def create
    @form = current_user.forms.create(form_params)
    if @form.save
      redirect_to @form, notice: 'Form was successfully created.'
    else
      flash[:error] = @form.errors.full_messages.to_sentence
      render :new
    end
  end
  
  def edit
    @form = Form.find(params[:id])
    if @form.fillings.count > 0
      flash[:error] = 'The form has already been filled and cannot be edited.'
      redirect_to request.referer
    end
  end
  
  def update
    @form = Form.find(params[:id])
    if @form.update_attributes(form_params)
      redirect_to @form, notice: 'Form was successfully updated.'
    else
      flash[:error] = @form.errors.full_messages.to_sentence
      render :edit
    end
  end
  
  def fill
    @filling = Filling.new(filling_params)
    @filling.form.questions.each do |question|
      @answer = @filling.answers.build
      @answer.category = question.category
      @answer.question_id = question.id
      if question.category == "text"
        @answer.content = params[question.id.to_s]
      elsif question.category == "number"
        @answer.content = params[question.id.to_s]
      elsif question.category == "date"
        @answer.date = params[question.id.to_s]
      elsif question.category == "multiple"
        @pick = @answer.picks.build
        @pick.choice_id = params[question.id.to_s]
        #unless  @pick.save
        #  flash[:error] = @pick.errors.full_messages.to_sentence
        #  raise ActiveRecord::Rollback
        #end
      elsif question.category == 'checkbox' || question.category == 'denture'
        if params[question.id.to_s]
          params[question.id.to_s].each do |choice_id|
            @pick = @answer.picks.build
            @pick.choice_id = choice_id
          end
        end
      elsif question.category == "dropdown"
        @pick = @answer.picks.build
        @pick.choice_id = params[question.id.to_s]
      end
      #unless  @answer.save
      #    flash[:error] = @answer.errors.full_messages.to_sentence
      #    raise ActiveRecord::Rollback
      #  end
    end
    if @filling.save
      redirect_to @filling, notice: 'Form was successfully filled.'
    else
      flash[:error] = @filling.errors.full_messages.to_sentence
      #flash[:error] = "The form contains #{@filling.errors.count} errors and could not be saved."
      @examination = @filling.examinations.build
      render :show
    end
  end

  def edit_fill
    @filling = Filling.find(params[:id])
    @filling.update(filling_params)
    @filling.answers.each do |answer|
      answer.destroy
    end
    @filling.form.questions.each do |question|
      @answer = @filling.answers.build
      @answer.category = question.category
      @answer.question_id = question.id
      if question.category == "text"
        @answer.content = params[question.id.to_s]
      elsif question.category == "number"
        @answer.content = params[question.id.to_s]
      elsif question.category == "date"
        @answer.date = params[question.id.to_s]
      elsif question.category == "multiple"
        @pick = @answer.picks.build
        @pick.choice_id = params[question.id.to_s]
        #unless  @pick.save
        #  flash[:error] = @pick.errors.full_messages.to_sentence
        #  raise ActiveRecord::Rollback
        #end
      elsif question.category == "checkbox" || question.category == 'denture'
        if params[question.id.to_s]
          params[question.id.to_s].each do |choice_id|
            @pick = @answer.picks.build
            @pick.choice_id = choice_id
          end
        end
      elsif question.category == "dropdown"
        @pick = @answer.picks.build
        @pick.choice_id = params[question.id.to_s]
      end
      #unless  @answer.save
      #    flash[:error] = @answer.errors.full_messages.to_sentence
      #    raise ActiveRecord::Rollback
      #  end
    end
    if @filling.save
      redirect_to @filling, notice: 'Filling was successfully edited.'
    else
      flash[:error] = @filling.errors.full_messages.to_sentence
      @examination = @filling.examinations.build
      render :show
    end
  end


  def stats

    @form = Form.find(params[:id])
    select = "SELECT count(*) AS countall"
    if params["question"].nil? or params["question"] == ""
      where = "WHERE e.filling_id = f.id AND form_id = #{params[:id]}"
      from = "FROM examinations e, fillings f"
    else
      where = "WHERE e.filling_id = f.id AND f.id = a.filling_id AND form_id = #{params[:id]}"
      from = "FROM examinations e, fillings f, answers a"
    end


    groupby = "GROUP BY"
    if params[:area] == "on"
      select += ", area"
      groupby += "#{groupby.length==8 ? ' ' : ', '}area"
    end
    if params[:date] == "on"
      if params[:from] != ""
        where += " AND e.date >= to_date('#{params[:from]}', 'DD/MM/YYYY')"
      end
      if params[:to] != ""
        where += " AND e.date <= to_date('#{params[:to]}', 'DD/MM/YYYY')"
      end
    end
    if params[:program] == "on"
      select += ", program"
      groupby += "#{groupby.length==8 ? ' ' : ', '}program"
    end
    if params[:doctor] == "on"
      select += ", doctor"
      groupby += "#{groupby.length==8 ? ' ' : ', '}doctor"
    end
    question = 0
    unless params["question"].nil? or params["question"] == ""
      where += " AND a.question_id = #{params["question"]}"
      select += ", a.content AS question"
      groupby += "#{groupby.length==8 ? ' ' : ', '}a.content"
    end
    @examinations = Examination.find_by_sql("#{select} #{from} #{where} #{groupby.length==8 ? "" : groupby}")
    @hash = {}
    @examinations.each do |e|
      hash = params["question"].nil? ? "" : "#{e.attributes["question"]}"
      hash += "#{params[:area]=="on" ? (hash.length>0 ? "-" : "") + e.area : ""}"
      hash +="#{params[:doctor]=="on" ? (hash.length>0 ? "-" : "") + e.doctor : ""}"
      hash +="#{params[:program]=="on" ? (hash.length>0 ? "-" : "") + e.program : ""}"
      @hash[hash] = e.countall
    end

  end


  def index
    if params[:query]
      @forms = Form.where("title LIKE \'%#{params[:query]}%\'").paginate(:page => params[:f_page], :per_page => 10)
      @my_forms = current_user.forms.where("title LIKE \'%#{params[:query]}%\'").paginate(:page => params[:mf_page], :per_page => 10) if current_user
    else  
      @forms = Form.paginate(:page => params[:f_page], :per_page => 10)
      @my_forms = current_user.forms.paginate(:page => params[:mf_page], :per_page => 10)  if current_user
    end
  end
  
  def show
    @form = Form.find(params[:id])
    @filling = @form.fillings.new
    @examination = @filling.examinations.build
  end
  
  def destroy
    Form.find(params[:id]).destroy
    redirect_to forms_path, :flash => {:success => 'Form destroyed.'}
  end

  def autocomplete_filling_area
    render json: Filling.select('DISTINCT area as value').where('LOWER(area) like LOWER(?)', "%#{params[:term]}%")
  end

  def autocomplete_examination_doctor
    render json: Examination.select('DISTINCT doctor as value').where('LOWER(doctor) like LOWER(?)', "%#{params[:term]}%")
  end

  def autocomplete_examination_program
    render json: Examination.select('DISTINCT program as value').where('LOWER(program) like LOWER(?)', "%#{params[:term]}%")
  end

  private

  def form_params
    params.require(:form).permit(:user_id, :title, :serial_enabled, :area_enabled, :date_enabled, :content_enabled, :doctor_enabled, :program_enabled, questions_attributes: [:id, :description, :category, :_destroy, choices_attributes: [:id, :content, :_destroy]])
  end
  
  def filling_params
    params.require(:filling).permit(:form_id, :serial, :area, examinations_attributes: [:id, :content, :date, :doctor, :program], answers_attributes: [:id, :content, :date, :category, :question_id, :_destroy, picks_attributes: [:id, :choice_id, :_destroy]])
  end
  
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_choice_fields.html.erb
<div class="nested-fields">
  <div class="field">
  	<table class="table">
            <tr>
                <td>
                    <input type="radio" disabled>
                </td>
                <td>
                    <%= f.text_field :content, :class => 'big' %>
                </td>
                <td>
                    <%= link_to_remove_association raw("<span class=\"glyphicon glyphicon-remove\"></span>"), f %>
                </td>
            </tr>
        </table>
  </div>
</div>

app/views/forms/_date_question_fields.html.erb
<div class="nested-fields transparent-box">
  <h4>Date question</h4>
  <div class="field">
    <%= f.hidden_field :category, :value => :date %>
    <table class="table">
      <tr>
        <td style="width:15%">
          <%= f.label :description %>
        </td>
        <td>
          <%= f.text_field :description, :class => 'big' %>
        </td>
        <td style="width:7%">
          <%= link_to_remove_association raw("<span class=\"glyphicon glyphicon-remove\"></span>"), f %>
        </td>
      </tr>
    </table>
  </div>
  <div style="clear: both;"></div>
</div>

app/views/forms/_denture_question_fields.html.erb
<div class="nested-fields transparent-box">
  <h4>Ερώτηση Οδοντοστοιχίας</h4>

  <div class="field">
    <%= f.hidden_field :category, :value => :denture %>
    <ta_text_question_fields.html.erbble class="table">
      <tr>
        <td style="width:15%">
          <%= f.label :description %>
        </td>
        <td>
          <%= f.text_field :description, :value => 'Εξέταση οδοντοστοιχίας', :class => 'big' %>
        </td>
        <td style="width:7%">
          <%= link_to_remove_association raw("<span class=\"glyphicon glyphicon-remove\"></span>"), f %>
        </td>
      </tr>
    </ta_text_question_fields.html.erbble>
  </div>

  <!--
  <div class="field">
    <%= f.hidden_field :category, :value => :denture %>
    <table class="table">
      <tr>
        <td style="width:15%">
          <%= f.label :description %>
        </td>
        <td>
          <%= f.text_field :description, :value => 'Εξέταση οδοντοστοιχίας', :class => 'big' %>
        </td>
        <td style="width:7%">
          <%= link_to_remove_association raw("<span class=\"glyphicon glyphicon-remove\"></span>"), f %>
        </td>
      </tr>
    </table>
  </div>
  -->
  <div style="clear: both;"></div>
</div>

app/views/forms/_edit_form.html.erb
<%= form_for @form do |f| %>
    <div class="field">
      <table class="table">
        <tr>
          <td style="width:15%"><%= f.label :title %></td>
          <td><%= f.text_field :title, :class => 'big' %></td>
        </tr>
      </table>
    </div>

    <div class="form-group">
      <%= f.label :serial_enabled, :class => 'checkbox form-control' do %>
          <%= f.check_box :serial_enabled %>Αύξων Αριθμός
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :area_enabled, :class => 'checkbox form-control' do %>
          <%= f.check_box :area_enabled %>Περιοχή
      <% end %>
    </div>
    <div id="examination">
      <h3>Ενεργά Πεδία Εξέτασης</h3>

      <div class="form-group">
        <%= f.label :date_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :date_enabled %>Ημερομηνία
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :content_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :content_enabled %>Παρατηρήσεις
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :doctor_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :doctor_enabled %>Ιατρός
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :program_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :program_enabled %>Πρόγραμμα
        <% end %>
      </div>
    </div>
    <div id="questions">
      <div class="links">
        <h3>Questions
          <div class="btn-group">
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle">Add a question
              <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><%= link_to_add_association 'Text question', f, :questions, {:partial => 'text_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Number question', f, :questions, {:partial => 'number_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Date question', f, :questions, {:partial => 'date_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Multiple choice', f, :questions, {:partial => 'multiple_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Checkbox', f, :questions, {:partial => 'checkbox_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Dropdown', f, :questions, {:partial => 'dropdown_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li class="divider"></li>
              <li><%= link_to_add_association 'Οδοντοστοιχία', f, :questions, {:partial => 'denture_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
            </ul>
          </div>
        </h3>
        <%= f.fields_for :questions, @form.questions.reverse do |question| %>
            <% if question.object.category == "text" %>
                <%= render 'text_question_fields', :f => question %>
            <% elsif question.object.category == "number" %>
                <%= render 'number_question_fields', :f => question %>
            <% elsif question.object.category == "date" %>
                <%= render 'date_question_fields', :f => question %>
            <% elsif question.object.category == "multiple" %>
                <%= render 'multiple_question_fields', :f => question %>
            <% elsif question.object.category == "checkbox" %>
                <%= render 'checkbox_question_fields', :f => question %>
            <% elsif question.object.category == "dropdowdn" %>
                <%= render 'dropdown_question_fields', :f => question %>

            <% elsif question.object.category == "denture" %>
                <%= render 'denture_question_fields', :f => question %>
            <% end %>
        <% end %>
      </div>

    </div>
    <%= f.submit 'Update', :class => 'btn btn-large btn-primary margin-top' %>
    <div class="huge-margin-top"></div>
<% end %>

app/views/forms/_form.html.erb
<%= form_for @form do |f| %>
    <div class="field">
      <table class="table">
        <tr>
          <td style="width:15%"><%= f.label :title %></td>
          <td><%= f.text_field :title, :class => 'big' %></td>
        </tr>
      </table>
    </div>

    <div class="form-group">
      <%= f.label :serial_enabled, :class => 'checkbox form-control' do %>
          <%= f.check_box :serial_enabled %>Αύξων Αριθμός
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :area_enabled, :class => 'checkbox form-control' do %>
          <%= f.check_box :area_enabled %>Περιοχή
      <% end %>
    </div>
    <div id="examination">
      <h3>Ενεργά Πεδία Εξέτασης</h3>

      <div class="form-group">
        <%= f.label :date_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :date_enabled %>Ημερομηνία
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :content_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :content_enabled %>Παρατηρήσεις
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :doctor_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :doctor_enabled %>Ιατρός
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :program_enabled, :class => 'checkbox form-control' do %>
            <%= f.check_box :program_enabled %>Πρόγραμμα
        <% end %>
      </div>
    </div>

    <div id="questions">
      <div class="links">
        <h3>Questions
          <div class="btn-group">
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle">Add a question
              <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><%= link_to_add_association 'Text question', f, :questions, {:partial => 'text_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Number question', f, :questions, {:partial => 'number_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Date question', f, :questions, {:partial => 'date_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Multiple choice', f, :questions, {:partial => 'multiple_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Checkbox', f, :questions, {:partial => 'checkbox_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li><%= link_to_add_association 'Dropdown', f, :questions, {:partial => 'dropdown_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
              <li class="divider"></li>
              <li><%= link_to_add_association 'Οδοντοστοιχία', f, :questions, {:partial => 'denture_question_fields', data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append}} %></li>
            </ul>
          </div>
        </h3>
        <%= f.fields_for :questions do |question| %>
            <% if question.object.category == "text" %>
                <%= render 'text_question_fields', :f => question %>
            <% elsif question.object.category == "number" %>
                <%= render 'number_question_fields', :f => question %>
            <% elsif question.object.category == "date" %>
                <%= render 'date_question_fields', :f => question %>
            <% elsif question.object.category == "multiple" %>
                <%= render 'multiple_question_fields', :f => question %>
            <% elsif question.object.category == "checkbox" %>
                <%= render 'checkbox_question_fields', :f => question %>
            <% elsif question.object.category == "dropdowdn" %>
                <%= render 'dropdown_question_fields', :f => question %>

            <% elsif question.object.category == "denture" %>
                <%= render 'denture_question_fields', :f => question %>

            <% end %>
        <% end %>
      </div>

    </div>
    <%= f.submit "Create", :class => "btn btn-large btn-primary margin-top" %>
    <div class="huge-margin-top"></div>
<% end %>

app/views/forms/_multiple_question_fields.html.erb
<div class="nested-fields transparent-box">
	<h4>Multiple choice question</h4>
    <div class="field">
    	<%= f.hidden_field :category, :value => :multiple %>
        <table class="table">
            <tr>
                <td style="width:15%">
                    <%= f.label :description %>
                </td>
                <td>
                    <%= f.text_field :description, :class => 'big' %>
                </td>
                <td style="width:7%">
                    <%= link_to_remove_association raw("<span class=\"glyphicon glyphicon-remove\"></span>"), f %>
                </td>
            </tr>
        </table>
    </div>
    <div id="choices" class="container col-xs-10">
        <div class="links">
            <h4>Choices <%= link_to_add_association 'Add a choice', f, :choices, :class => "btn btn-default", :role => "button", data: {:'association-insertion-traversal' => 'closest', :'association-insertion-node' => '.links', :'association-insertion-method' => :append} %>
            </h4>
          <%= f.fields_for :choices, f.object.choices do |choice| %>
            <%= render 'choice_fields', :f => choice %>
            <% end %>
        </div>
    </div>
	<div style="clear: both;"></div>
</div>

app/views/forms/_task_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :description %>
    <br/>
    <%= f.text_field :description %>
  </div>
  <%= link_to_remove_association "remove question", f %>
</div>

app/views/forms/edit.html.erb
<div class="container col-xs-7 center text-center">
  <h2 class="form-signin-heading">New form</h2>

<%= render 'edit_form' %>

</div> <!-- /container -->

app/views/forms/index.html.erb
<% if current_user %>
<div class="transparent-box text-center">
    <h3>My forms</h3>
    <div class="big-margin-top">
        <%= will_paginate @my_forms, :param_name => 'mf_page' %>
        <table class="table table-nonfluid center">
            <tbody>
                <% @my_forms.each do |form| %>
                <tr>
                    <td>
                      <%= link_to "#{form.title}: Filled #{form.fillings.size} time(s)", fillings_index_path(form) %>
                    </td>
                    <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-pencil\"></span> Fill"), form %>
                    </td>
                    <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-edit\"></span> Edit"), edit_form_path(form) %>
                    </td>
                    <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-remove\"></span> Remove"), form, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  <td>
                    <%= link_to raw("<span class=\"glyphicon glyphicon-download\"></span> CSV"), fillings_index_path(form, format: 'csv') %>
                  </td>
                  <td>
                    <%= link_to raw("<span class=\"glyphicon glyphicon-download\"></span> Excel"), fillings_index_path(form, format: 'xls') %>
                  </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate @my_forms, :param_name => 'mf_page' %>
    </div>
</div>
<% end %>

<div class="transparent-box text-center">
    <h3>All forms</h3>
    <div class="big-margin-top">
        <%= will_paginate @forms, :param_name => 'f_page' %>
        <table class="table table-nonfluid center">
            <tbody>
                <% @forms.each do |form| %>
                <tr>
                    <td>
                        <%= form.title %>
                    </td>
                    <td>
                        <%= link_to "Filled #{form.fillings.size} time(s)", fillings_index_path(form) %>
                    </td>
                    <td>
                      <%= link_to "Charts", stats_path(form) %>
                    </td>
                    <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-pencil\"></span> Fill"), form %>
                    </td>
		    <% if current_user %>
                    <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-edit\"></span> Edit"), edit_form_path(form) %>
                    </td>
                    <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-remove\"></span> Remove"), form, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                      <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-download\"></span> CSV"), fillings_index_path(form, format: 'csv') %>
                      </td>
                      <td>
                        <%= link_to raw("<span class=\"glyphicon glyphicon-download\"></span> Excel"), fillings_index_path(form, format: 'xls') %>
                      </td>

                <% end %>
                </tr>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate @forms, :param_name => 'f_page' %>
    </div>
</div>

app/views/forms/show.html.erb
<div class="container col-xs-7 center text-center">
  <h2><%= link_to @filling.form.title, fillings_index_path %>

  </h2>
  <%= form_for @filling, :url => {:controller => 'forms', :action => 'fill'} do |f| %>
      <%= f.hidden_field :form_id, :value => params[:id] %>
      <% if @filling.form.serial_enabled %>
      <div class="transparent-box">
        <h4>Αύξων Αριθμός Ασθενούς</h4>
        <%= f.number_field :serial, :class => 'big' %>
      </div>
      <% end %>
      <% if @filling.form.area_enabled %>
          <div class="transparent-box">
            <h4>Περιοχή</h4>
            <%= f.autocomplete_field :area, autocomplete_filling_area_forms_path, :class => 'big' %>
          </div>
      <% end %>
      <% @filling.form.questions.reverse.each do |question| %>
          <div class="nested-fields transparent-box">
            <h4><%= question.description %></h4>
            <% if question.category == "text" %>
                <%= render :partial => "/fillings/text_answer_fields", :locals => {:question_id => question.id} %>
            <% elsif question.category == "number" %>
                <%= render :partial => "/fillings/number_answer_fields", :locals => {:question_id => question.id} %>
            <% elsif question.category == "date" %>
                <h6>(ΗΗ/ΜΜ/ΕΕΕΕ)</h6>
                <%= render :partial => "/fillings/date_answer_fields", :locals => {:question_id => question.id} %>
            <% elsif question.category == "multiple" %>
                <table class="table table-nonfluid text-left">
                  <% question.choices.each do |choice| %>
                      <%= render :partial => "/fillings/multiple_answer_fields", :locals => {:question_id => question.id, :content => choice.content, :choice_id => choice.id} %>
                  <% end %>
                </table>
            <% elsif question.category == "checkbox" %>
                <table class="table table-nonfluid text-left">
                  <% question.choices.each do |choice| %>
                      <%= render :partial => "/fillings/checkbox_answer_fields", :locals => {:question_id => question.id, :content => choice.content, :choice_id => choice.id} %>
                  <% end %>
                </table>
            <% elsif question.category == 'denture' %>
                <%= render :partial => "/fillings/denture_answers_fields", :locals => {:question => question} %>
            <% elsif question.category == "dropdown" %>
                <select class="form-control" name="<%= question.id %>">
                  <% question.choices.each do |choice| %>
                      <%= render :partial => "/fillings/dropdown_answer_fields", :locals => {:question_id => question.id, :content => choice.content, :choice_id => choice.id} %>
                  <% end %>
                </select>

            <% end %>
          </div>
      <% end %>
      <% @count = 1 %>
      <%= f.fields_for :examinations, f.object.examinations do |e| %>
          <%= render :partial => '/fillings/examination', :locals => {:e => e, :disabled => FALSE, :count => @count, :date => e.object.date.blank? ? '' : e.object.date.strftime('%d/%m/%Y')} %>
          <% @count += 1 %>
      <% end %>
      <%= f.submit "Submit", :class => "btn btn-large btn-primary margin-top" %>
  <% end %>
</div>
<!-- /container -->