config/routes.rb
Rails.application.routes.draw do
  resources :databases

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :forms do
    get :autocomplete_examination_doctor, :on => :collection
    get :autocomplete_examination_program, :on => :collection
    get :autocomplete_filling_area, :on => :collection
  end
  resources :fillings
  resources :databases

  get '/inactive', to: 'users#index_inactive', as: :inactive
  get '/manage', to: 'users#index', as: :manage
  match '/users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  post '/enable/:id',  to: 'users#enable'    , as: :enable
  match '/forms/:id/fill', to: 'forms#fill'  , as: :fill      , via: [:post, :patch]
  match '/fillings/:id/edit', to: 'forms#edit_fill'  , as: :edit_fill      , via: [:post, :patch]
  get '/forms/:id/stats', to: 'forms#stats', as: :stats
  get '/forms/:id/fillings', to: 'fillings#form_index', as: :fillings_index

  root to: 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by MaDgIK
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar-nav navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
    		<img style="float:left; margin-right:12px; margin-top:5px; margin-bottom:5px; height:60px" src="http://mdmgreece.gr/app/themes/mdm/assets/img/mdmgreece.png">
        <%= link_to "MDM forms", root_path, id: "logo" %>
        <% if signed_in? %>
        <div class="col-sm-3 col-md-3">
            <form class="navbar-form" role="search" action="/forms" method="get" id="search-form" name="search-form">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." id="query" name="query" value="">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <ul class="nav navbar-nav navbar-right">
        	<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-book"></span>  <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
	          <li><%= link_to "Create Form", new_form_path %></li>
	          <li><%= link_to "View Forms", forms_path %></li>
                </ul>
            </li>
            <% if current_user.admin %>
			<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span>  <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
	          <li><%= link_to "Manage users", manage_path %></li>
	          <li><%= link_to "Manage inactive users", inactive_path %></li>
                </ul>
            </li>
			<% end %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
		    <li>
                        <%= link_to "Edit Profile", edit_user_registration_path %>
                    </li>		    
		    <li class="divider">
                    <li>
                        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                    </li>
                </ul>
            </li>
        </ul>

        <% else %>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <%= link_to "Sign in", new_user_session_path %>
            </li>
        </ul>
        <% end %>
    </div>
</nav>